services:
    db:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        env_file: .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        command: ["postgres", "-N", "5000"]
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        deploy:
          resources:
            limits:
              cpus: '5.0'
            reservations:
              cpus: '4.0'

    rails:
        container_name: rails-app
        build: .
        command: "./bin/rails server -b 0.0.0.0"
        environment:
            - RAILS_ENV=${RAILS_ENV}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        volumes:
            - .:/rails
            - app-storage:/rails/storage
            - ../out:/out
        depends_on:
            - db
        ports:
            - "3000:3000"
        deploy:
          resources:
            limits:
              cpus: '9.0'

volumes:
    postgres-data: {}
    app-storage: {}
