# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks
namespace :tsv do
  desc "Parse TSV file"
  task :parse do
    path = '../out/title.basics.tsv'

    TSV[path].each_with_index.map do |row, i|
      break if i > 10

      puts row['primaryTitle']
    end

    parsed = TSV.parse_file(path)
    puts parsed.size

    # puts TSV.parse_file("../out/title.basics.tsv").without_header.first.to_h
  end
end
